[template]
  incoming-hooks = ["Contentful"]

[template.environment]
  CONTENTFUL_SPACE_ID = "ngu2am8g6zzc"
  CONTENTFUL_ACCESS_TOKEN = "I4-zYL6W0bIpDWRyXwZKysIbfZtUoeBW50I-0QGsYC0"
  CONTENTFUL_PREVIEW_ACCESS_TOKEN = "uaxqL6SZrDnqMRBmsKq8BZaEznUyeT2jsq1B6RcgBiY"
